config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  get 'admin/dashboard' => 'admin#index', :as => 'admin_dashboard'
  get 'admin/review/:wiki_version_id' => 'admin#edit', :as => 'admin_review_wiki'
  put 'admin/update/:wiki_version_id' => 'admin#update', :as => 'admin_update_wiki'

  resources :wikis, :only => [:show, :edit, :update]
  resources :comments, :only => [:new, :create]

  get 'wiki_versions/:wiki_id/history' => 'wiki_versions#history', :as => 'wiki_version_history'
  get 'wiki_versions/:id/diff/' => 'wiki_versions#diff', :as => 'wiki_version_diff'
  post 'textile_preview' => 'textile#preview', :as => 'textile_preview'

  root :to => 'home#index'

end

app/views/admin/_action_buttons.html.haml
= submit_tag t(:save_button), :class => 'save_button', :name => 'commit', 'data-confirm' => "பாடல் ஒப்புதலை உறுதி செய்க ..."
= submit_tag t(:reject_button), :class => 'reject_button', :name => 'commit', 'data-confirm' => "மறுத்தலை உறுதி செய்க ..."
%span.action_button
  %a{:href=> admin_dashboard_path}
    %img.back_to_show{:src => '/images/first.png'}

app/views/admin/_edit_with_diff.html.haml
- if changed_attributes.include? attribute
  = label(:wiki_version, attribute)
  #differ= raw generate_diff(wiki_version.send(attribute), wiki_version.wiki.send(attribute))
  - unless attribute == :tamil_long_desc
    = wiki_form.text_field attribute
  - else
    = raw textile_editor 'wiki_version', 'tamil_long_desc', {:rows => 20, :cols => 75, :wrap => 'soft'}
    = raw textile_editor_initialize
    %br
    %label
      %span.textile_preview{:url => textile_preview_path} முன்காட்சி
    #preview_container.wiki_container
      %p{:style => 'text-align: justify;'}
        = raw wiki_version.tamil_long_desc_html

- else
  = label(:wiki_version, attribute)
  = wiki_version.send(attribute)

app/views/admin/edit.html.haml
= stylesheet_link_tag 'compiled/admin'
= render :partial => 'common/google_transliterate'

:javascript
  jQuery.noConflict();
  jQuery(document).ready(function(){
    jQuery('#keyboard').click(function(){
      window.location.href = "?tamil_keyboard=true";
    });
  });

= javascript_include_tag 'jquery.observe_field.js'
= javascript_include_tag 'https://ajax.googleapis.com/ajax/libs/prototype/1.7.0.0/prototype.js'
= javascript_include_tag 'textile-editor'
= javascript_include_tag 'textile-editor-config'
= javascript_include_tag 'textile_preview'
= stylesheet_link_tag 'textile-editor'

- unless flash.now[:error].blank?
  .error= flash.now[:error]
- else
  - user = @wiki_version.user
  .revision_user_info
    .sub_heading
      %span.photo
        %img.profile_photo{:src => "#{user.photo || '/images/default_photo.png' }"}
      .user_details
        %ul
          %li
            %b
              = user.name
          %li
            சமர்ப்பித்தவை:
            = user.accepted_count + user.rejected_count
          %li
            பிரசுரமானவை:
            = user.accepted_count
  .clear
  = form_for @wiki_version, :url => admin_update_wiki_path(@wiki_version) do |wiki_form|

    = render :partial => 'action_buttons'

    - Wiki.essential_attribute_names.each do |attribute|
      %p.wiki_revision_attribute
        = render :partial => 'edit_with_diff', :locals => {:wiki_version => @wiki_version, :attribute => attribute.to_sym,
                                             :changed_attributes => @changed_attributes, :wiki_form => wiki_form}

    = render :partial => 'action_buttons'

:javascript
  var transliterable_elements = [];
  jQuery.each(['wiki_version_tamil_short_desc', 'wiki_version_tamil_long_desc'], function(index,value){
    if (jQuery('#' + value).length){
      transliterable_elements.push(value);
    }
  });
  makeTransliteratable(transliterable_elements);

app/views/admin/index.html.haml
= stylesheet_link_tag 'compiled/admin'
= stylesheet_link_tag 'admin_table'


.dashboard_title
  %span.sub_title தளப் பொறுப்பாளரின் முகப்பு 

- unless flash[:notice].blank?
  .notice= flash[:notice]

.sub_heading
  அண்மையில் சமர்ப்பித்த திருத்தங்கள்

%table#drafts
  %thead
    %tr
      %th{:scope => 'col'} நேரம்
      %th{:scope => 'col'} பாடல்
      %th{:scope => 'col'} முன்வைத்தவர்
      %th{:scope => 'col'} ஆய்வு செய்க
  %tbody
    - @draft_wikis.each do |draft_wiki|
      %tr{:class => "#{cycle("", "odd")}"}
        %td.time= l draft_wiki.created_at, :format => :short
        %td.paadal= draft_wiki.paadal
        - user_name = draft_wiki.user.name || draft_wiki.user.email.truncate(30)
        %td.user= user_name
        %td.view
          %a{:href => admin_review_wiki_path(draft_wiki)}
            %img.review{:src => '/images/review.png'}