config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  get 'admin/dashboard' => 'admin#index', :as => 'admin_dashboard'
  get 'admin/review/:wiki_version_id' => 'admin#edit', :as => 'admin_review_wiki'
  put 'admin/update/:wiki_version_id' => 'admin#update', :as => 'admin_update_wiki'

  resources :wikis, :only => [:show, :edit, :update]
  resources :comments, :only => [:new, :create]

  get 'wiki_versions/:wiki_id/history' => 'wiki_versions#history', :as => 'wiki_version_history'
  get 'wiki_versions/:id/diff/' => 'wiki_versions#diff', :as => 'wiki_version_diff'
  post 'textile_preview' => 'textile#preview', :as => 'textile_preview'

  root :to => 'home#index'

end

app/views/user_notifier/welcome_mail.html.haml
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
  %body
    %p
      தமிழ் அன்பரே,
    %p
      வணக்கம்.
    %p
      தாம் எமது இணைய தளத்தில் தங்களை இணைத்துக்கொண்டதற்கு மிக்க நன்றி. தங்களின் இந்த நற்செயலுக்கு தமிழ்ப் பற்றே தூண்டுகோல் என்பதை நாங்கள் நன்கறிவோம். அந்தப் பற்றுக்கு பசியாற்றுவது எமது முதற்கடமை என்பதை இத்தருணத்தில் தங்களுக்கு பணிவன்புடன் தெரிவித்துக்கொள்கிறோம்.
    %p
      எங்கள் இணைய தளத்தின் சேவைகளைப் பற்றி அறிய, "இணைய தளத்தைப் பற்றி" என்ற பகுதி தங்களுக்கு உதவும். எங்களின் சேவையில் ஏதேனும் சிறு குறை இருப்பினும் தாங்கள் தயங்காது எங்களுக்கு தெரிவிப்பீராக.
    %p
      தங்களின் ஒவ்வொரு வரவும் நல்வரவாக வாழ்த்துக்கள்.
    %p
      நன்றியுடன்,
      %br
      தளப் பொறுப்பாளர்கள்.
      %br
      = link_to "அறம்செயவிரும்பு.com", root_url

app/views/user_notifier/wiki_approved_mail.html.haml
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
  %body
    %p
      தமிழ் அன்பரே,
    %p
      வணக்கம்.
    %p
      "
      %b
        = link_to @wiki_version.paadal, wiki_url(@wiki_version.wiki)
      " பகுதியில் தாங்கள் செய்த திருத்தங்கள் தளப் பொறுப்பாளர்களால் ஏற்கப்பட்டது என்பதை மகிழ்ச்சியுடன் தெரிவித்துக்கொள்கிறோம்.
    %p
      தங்களின் தமிழ் சேவைக்கு நன்றி. இந்த சேவையின் தேவை அறிந்ததின் மூலம் நாம் ஒரே நோக்கத்தோடு பயணிக்கின்றோம். தங்களின் ஆதரவுடன் தொடர்ந்து பயணிப்பதில் எங்களுக்கு மட்டற்ற மகிழ்ச்சியே.
    %p
      நன்றியுடன்,
      %br
      தளப் பொறுப்பாளர்கள்.
      %br
      = link_to "அறம்செயவிரும்பு.com", root_url