config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  get 'admin/dashboard' => 'admin#index', :as => 'admin_dashboard'
  get 'admin/review/:wiki_version_id' => 'admin#edit', :as => 'admin_review_wiki'
  put 'admin/update/:wiki_version_id' => 'admin#update', :as => 'admin_update_wiki'

  resources :wikis, :only => [:show, :edit, :update]
  resources :comments, :only => [:new, :create]

  get 'wiki_versions/:wiki_id/history' => 'wiki_versions#history', :as => 'wiki_version_history'
  get 'wiki_versions/:id/diff/' => 'wiki_versions#diff', :as => 'wiki_version_diff'
  post 'textile_preview' => 'textile#preview', :as => 'textile_preview'

  root :to => 'home#index'

end

app/views/admin_notifier/notify_wiki_submission.html.haml
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
  %body
    %p
      தமிழ் அன்பரே,
    %p
      வணக்கம்.
    %p
      கீழ்கண்ட பகுதி திருத்தப்பட்டு தங்களின் ஒப்புதலுக்காக சமர்ப்பிக்கப்பட்டுள்ளது.
    %p
      திருத்தியவர்: #{@wiki_version.user.display_name}
      %br
      திருத்திய பாடல்: #{@wiki_version.paadal}
    %p
      திருத்தங்கள் ஏற்புடையதாயின் தங்களது ஒப்புதலையும், அல்லது மறுதலிக்க வேண்டின் உரிய காரணங்களையும் தளத்தில் பதிவு செய்யுமாறு கேட்டுக்கொள்கிறோம்.
    %p
      மாற்றங்களை காண இந்த
      =link_to "இணைப்பை ", admin_review_wiki_url(@wiki_version)
      அழுத்தவும்.
    %p
      தங்கள் ஒத்துழைப்பிற்கு நன்றி.
    %p
      நன்றியுடன்,
      %br
      தளப் பொறுப்பாளர்கள்.
      %br
      = link_to "அறம்செயவிரும்பு.com", root_url